#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none) //this code does not contain ebola
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorC,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorD,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone) // not sure why there are all of these extra motors
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone) //that are not being used
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*// ah, thats why

//#include "JoystickDriver.c" // adds file to take bt controllers, comp only <============ change for comp =======================

/* Some configuration/wiring settings for this code:
 first wire goes to right motor, second to left
*/



	void startup(){ //this is some settup stuff
		getJoystickSettings(joystick);//updates joystick

		//variable setup
		int jBuffer = 25; //buffer for joysticks
		int sTime = 10; //sleep time, reaction time
		int dSpeed = 50; //drive speed
		int tSpeed = 20; //turning speed

		//button setup
		int bX = 0;
		int bA = 1;
		int bB = 2;
		int bY = 3;
		int LB = 4;
		int RB = 5;
		int LT = 6;
		int RT = 7;
		int bBack = 8;
		int bStart = 9;
		//mode button does not do anything
	} //end of startup



task main(){//the start of the robot acutally doing things

	startup();//pulls startup things and does them here

 	//waitForStart(); //waits for driving period to start, only in comp <================== change for comp =====================

	while(true){

		getJoystickSettings(joystick);//updates joystick

		if(abs(joystick.joy1_x1) < jBuffer && abs(joystick.joy1_y1) < jBuffer){ //stop
			motor[motorA] = 0;
			motor[motorB] = 0;
			sleep = sTime;

	}

		if(abs(joystick.joy1_x1) < jBuffer && (joystick.joy1_y1) > jBuffer){ //forwards
			motor[motorA] = dSpeed;
			motor[motorB] = dSpeed;
			sleep = sTime;

	}

		if(abs(joystick.joy1_x1) < jBuffer && (joystick.joy1_y1) < -jBuffer){ //backwards
			motor[motorA] = -dSpeed;
			motor[motorB] = -dSpeed;
			sleep = sTime;

	}

		if((joystick.joy1_x1) > jBuffer && abs(joystick.joy1_y1) < jBuffer){ //right point
			motor[motorA] = tSpeed;
			motor[motorB] = -tSpeed;
			sleep = sTime;

	}

		if((joystick.joy1_x1) < -jBuffer && abs(joystick.joy1_y1) < jBuffer){ //left point
			motor[motorA] = -tSpeed;
			motor[motorB] = tSpeed;
			sleep = sTime;

	}

		if((joystick.joy1_x1) > jBuffer && (joystick.joy1_y1) > jBuffer){ //forwards right swing
			motor[motorA] = 0;
			motor[motorB] = tSpeed;
			sleep = sTime;

	}

		if((joystick.joy1_x1) > jBuffer && (joystick.joy1_y1) < -jBuffer){ //backwards right swing
			motor[motorA] = 0;
			motor[motorB] = -tSpeed;
			sleep = sTime;

	}

		if((joystick.joy1_x1) < -jBuffer && (joystick.joy1_y1) > jBuffer){ //forwards left swing
			motor[motorA] = 0;
			motor[motorB] = tSpeed;
			sleep = sTime;

	}

		if((joystick.joy1_x1) < -jBuffer && (joystick.joy1_y1) < -jBuffer){ //backwards left swing
			motor[motorA] = ;
			motor[motorB] = -tSpeed;
			sleep = sTime;

	}

}//end of while true loop
}//end of task main
